---
language: python
python: "2.7"

install:
  - pip install ansible
  - sudo apt install -y systemd

script:
  # Test Redis Sentinel
  - "ansible-playbook -i localhost, test/testpx.yml --connection=local --become-user root"
  # Wait for PX to come up
  - "sleep 180"
  # Show the log
  - "sudo journalctl -lu portworx"
  # Connection test
  - "sudo /opt/pwx/bin/pxctl status"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
