---
language: python
python: "2.7"
sudo: required
dist: trusty
addons:
  hosts:
    - pxetcd.dev

install:
  - pip install ansible
  - sudo apt install -y systemd
  # Make loopback device for px to use
  - sudo mknod -m660 /dev/dm6 b 7 18
  - sudo touch /var/loop_device_file
  - sudo truncate -s 64G /var/loop_device_file
  - sudo losetup /dev/dm6 /var/loop_device_file
  - sudo ip a
  - docker run --net=host \
   -d --name etcd-v3.1.3 \
   --volume=/tmp/etcd-data:/etcd-data \
   quay.io/coreos/etcd:v3.1.3 \
   /usr/local/bin/etcd \
   --name my-etcd-1 \
   --data-dir /etcd-data \
   --listen-client-urls http://0.0.0.0:2379 \
   --advertise-client-urls http://pxetcd.dev:2379 \
   --listen-peer-urls http://0.0.0.0:2380 \
   --initial-advertise-peer-urls http://pxetcd.dev:2380 \
   --initial-cluster my-etcd-1=http://pxetcd.dev:2380 \
   --initial-cluster-token my-etcd-token \
   --initial-cluster-state new \
   --auto-compaction-retention 1
 

script:
  # Test PX
  - "ansible-playbook -i localhost, test/testpx.yml --connection=local --become-user root --extra-vars 'kvdb=\"-k pxetcd.dev:2379\" mgmt_if=\"-m eth0\" data_if=\"-d eth0\" device_args=\"-s /dev/dm6\"'"
  # Wait for PX to come up
  - "sleep 240"
  # Show the log
  - "sudo journalctl -u portworx"
  - "sudo systemctl status portworx"
  # Connection test
  - "sudo /opt/pwx/bin/pxctl status"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
