---
language: python
python: "2.7"
sudo: required
dist: trusty

install:
  - pip install ansible
  - sudo apt install -y systemd
  # Make loopback device for px to use
  - sudo mknod -m660 /dev/dm6 b 7 18
  - sudo touch /var/loop_device_file
  - sudo truncate -s 64G /var/loop_device_file
  - sudo losetup /dev/dm6 /var/loop_device_file
  - sudo ip a

script:
  # Test PX
  - "ansible-playbook -i localhost, test/testpx.yml --connection=local --become-user root --extra-vars 'kvdb=\"\" mgmt_if=\"-m eth0\" data_if=\"-d eth0\" device_args=\"-s /dev/dm6\"'"
  # Wait for PX to come up
  - "sleep 240"
  # Show the log
  - "sudo journalctl -u portworx"
  - "sudo systemctl status portworx"
  # Connection test
  - "sudo /opt/pwx/bin/pxctl status"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
