---
language: python
python: "2.7"

install:
  - pip install ansible
  - sudo apt install -y systemd

script:
  # Test Redis Sentinel
  - "ansible-playbook -i localhost, test/testpx.yml --connection=local --sudo"
  # Connection test
  - "/opt/pwx/bin/pxctl status"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
